apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frontend-master
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /frontend

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frontend
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /frontend
