subcomponents:
  chart:
    config:
      image:
        repository: hellorings.azurecr.io/samiyaakhtar/hello-world-full-stack-backend
        tag: master-20200603.10
      serviceName: backend-master
