subcomponents:
  chart:
    config:
      image:
        repository: hellorings.azurecr.io/samiyaakhtar/hello-world-full-stack-frontend
        tag: master-20200603.13
      serviceName: frontend-master
